#!/usr/bin/env bash
# Function to get the DNS information for a subdomain
get_dns_info() {
    subdomain=$1
    domain=$2

    dig_output=$(dig ${subdomain}.${domain} | awk '/^;; ANSWER SECTION:$/,/^$/' | awk 'NR > 1')
    record_type=$(echo "${dig_output}" | awk '{print $4}')
    destination=$(echo "${dig_output}" | awk '{print $5}')
    
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

# Check the number of arguments
if [ $# -eq 1 ]; then
    get_dns_info www $1
    get_dns_info lb-01 $1
    get_dns_info web-01 $1
    get_dns_info web-02 $1
elif [ $# -eq 2 ]; then
    get_dns_info $2 $1
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
